# Numpy Practice

https://www.w3schools.com/python/numpy/default.asp

NumPy is used for working with arrays. NumPy is short for "Numerical Python". It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In Python we have lists that serve the purpose of arrays, but they are slow to process. **NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**

The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.



In [70]:
import numpy as np
#create an array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [71]:
#Tuple to array
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


2-dimensional arrays

In [72]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr)

[1 2 3 4 5]


3-D Arrays (Tensors)

In [73]:
arr3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]]]


Check number of dimensions.

In [74]:
arr3.ndim

3

In [75]:
arr.ndim

1

Access elements in array

In [76]:
arr1 = np.array([1,2,3,4,5])
print(arr1[4])

5


In [77]:
#acess element in 2D array
print(arr2[1,2])

6


In [78]:
#acess element in 3D array
print(arr3[1,1,1])

8


In [79]:
#Print range
print(arr1[1:4])

[2 3 4]


In [80]:
print(arr1[:3])

[1 2 3]


In [81]:
print(arr1[3:])

[4 5]


In [82]:
#access every other value in array

In [84]:
arr1[0:5:2]

array([1, 3, 5])

## Shape of an Array

In [32]:
arr2.shape

(2, 3)


In [33]:
arr1.shape

(5,)

In [34]:
arr3.shape

(2, 2, 3)

## Reshape an Array

In [38]:
arr_long = np.array([1,2,3,4,5,6,7,8,9,10])
arr4 = arr_long.reshape(2,5)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Flatten a multidimensional array into 1-D

In [40]:
arr5 = arr4.reshape(-1)
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10]


## Itterate on an Array

In [51]:
ls = []
arr6 = np.array([])

for i in arr5:
    ls.append(i/5)
    
#print(arr6)
#Convert list back to array
arr7 = np.array(ls)
print(arr7)

[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


## Joining Arrays

In [58]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

#Join arrays
arr_3 = np.concatenate((arr_1, arr_2))
print(arr_3)

[1 2 3 4 5 6]


Stacking along columns

In [60]:
arr_3_stack = np.vstack((arr_1, arr_2))
print (arr_3_stack)

[[1 2 3]
 [4 5 6]]


## Search Arrays

In [63]:
arr_s = np.array([2, 5, 3, 7, 2, 23, 5, 76 ,12 , 44, 2, 5, 76, 9, 45, 22, 2, 1])

#Will return location of the value of 2
x = np.where(arr_s == 2)
print(x)

(array([ 0,  4, 10, 16]),)


## Sort Arrays

In [64]:
#sort arr_s array
arr_sort = np.sort(arr_s)
print(arr_sort)

[ 1  2  2  2  2  3  5  5  5  7  9 12 22 23 44 45 76 76]


In [65]:
#alphabetical sort

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


## Filter Arrays
Filter out specific value that meet certain logic criteria.

In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

#create emply list
ls_filt = []

for i in arr:
    #only add value is it is complete divisible by 2
    if i % 2 == 0:
        ls_filt.append(i)
#convert list to array
arr_filt = np.array(ls_filt)
        
print(arr_filt)

[ 2  4  6  8 10]
